export default {
  sems:[
    {code:"1401-01","title":"ترم پاییز 1401",majors:["ElecEng","MechEng","CivilEng"]},
    {
      code:"1400-02",
      title:"ترم بهار 1400",
      majors: [
        "Commu",
        "EngPhys",
        "Stats",
        "BioTech",
        "Law",
        "Physics",
        "CS",
        "Painting",
        "CivilEng",
        "PolEng",
        "UrbnEng",
        "IndEng",
        "Econ",
        "ElecEng",
        "Mngmnt",
        "MechEng",
        "Metallurgy",
        "CompEng",
        "EngSci",
        "Math",
        "OilEng",
        "Geography",
        "MineEng",
        "Psychology",
        "SurvEng",
        "ChemEng",
        "Arch",
        "GrdnngEng",
        "FoodSci",
        "MechBio",
        "CompEngFar",
        "AppChem"
      ],
    }
  ],
  
  currentSemester: "1401-01",
  majors: [
    "Commu",
    "EngPhys",
    "Stats",
    "BioTech",
    "Law",
    "Physics",
    "CS",
    "Painting",
    "CivilEng",
    "PolEng",
    "UrbnEng",
    "IndEng",
    "Econ",
    "ElecEng",
    "Mngmnt",
    "MechEng",
    "Metallurgy",
    "CompEng",
    "EngSci",
    "Math",
    "OilEng",
    "Geography",
    "MineEng",
    "Psychology",
    "SurvEng",
    "ChemEng",
    "Arch",
    "GrdnngEng",
    "FoodSci",
    "MechBio",
    "CompEngFar",
    "AppChem"
  ],
};

export let majorsList = [
  ["_Blank", "برد خالی", "mdi-account-hard-hat"],
  ["CivilEng", "مهندسی عمران", "mdi-account-hard-hat"],
  ["MechEng", "مهندسی مکانیک", "mdi-tools"],
  ["ElecEng", "مهندسی برق", "mdi-flash"],
  ["IndEng", "مهندسی صنایع", "mdi-factory"],
  ["CompEng", "مهندسی کامپیوتر", "mdi-code-array"],
  ["ChemEng", "مهندسی شیمی", "mdi-flask"],
  ["Metallurgy", "مهندسی مواد", "mdi-cup"],
  ["Math", "ریاضیات و کاربرد ها", "mdi-math-integral"],
  ["CS", "علوم کامپیوتر", "mdi-code-braces-box"],
  ["OilEng", "مهندسی نفت", "mdi-barrel"],
  ["Arch", "معماری", "mdi-math-compass"],
  ["EngSci", "علوم مهندسی", "mdi-rocket"],
  ["SurvEng", "مهندسی نقشه برداری", "mdi-map"],
  ["MineEng", "مهندسی معدن", "mdi-gantry-crane"],
  ["BioTech", "بیوتکنولوژی", "mdi-microscope"],
  ["PolEng", "مهندسی پلیمر", "mdi-seed"],
  ["UrbnEng", "مهندسی شهرسازی", "mdi-city-variant-outline"],
  ["Geography", "جغرافیا", "mdi-earth"],
  ["Stats", "آمار", "mdi-chart-box"],
  ["Physics", "فیزیک", "mdi-alpha"],
  ["Psychology", "روانشناسی", "mdi-brain"],
  ["Mngmnt", "مدیریت", "mdi-account-tie"],
  ["Law", "حقوق", "mdi-scale-balance"],
  ["Econ", "اقتصاد", "mdi-chart-areaspline"],
  ["Painting", "نقاشی", "mdi-brush"],
  ["EngPhys", "فیزیک مهندسی", "mdi-bike-fast"],
  ["Commu", "علوم ارتباطات", "mdi-chat"],
  ["GrdnngEng", "مهندسی باغبانی", "mdi-tree"],
  ["FoodSci", "مهندسی صنایع غذایی", "mdi-food"],
  ["MechBio","مکانیک بیوسیستم",'mdi-bio'],
  ["CompEngFar", "کامپیوتر (فارابی)", "mdi-code-array"],
  ["AppChem","شیمی کاربردی","mdi-flask-round-bottom-outline"]
];
